### ISSUE TITLE
‘substring(6,7)’  ?

### ISSUE THREAD

**Issue by tflo** [vaetas/hugo-footnotes-popup#5]
With `const index = node.id.substring(6,7);` you are just getting the first character of the string.

It happens that I name my footnotes by something semantically more expressive, like for example `[^usage]` (instead of `[^1]`).

In these cases your substring implementation will fail. (And also if you have numerical footnote numbers > 9).

So, why not change it to…
```
const index = node.id.substring(6);
```

This would take all characters, starting at position 6, but not limited to position 6.

As already said in the [other issue post](https://github.com/vaetas/hugo-footnotes-popup/issues/4#issue-464352517), I’m a JS-ignorant, so, please let me know if/why this would be no good.

**Comment by vaetas** [comment]
Hello Tom,
sorry for late reply, I was busy recently.

You are completely right, current implementation will fail on your given footnotes. It's shame I completely forgot to test these cases. 

I will update the code right now. I hope, however, it will not break anything else.

**Comment by tflo** [comment]
>  I hope, however, it will not break anything else.

_So far,_ it works fine for me with these types of footnotes:

- `[^1]`
- `[^12]`
- `[^blahblah]`

– Tom
